"""initial migrating

Revision ID: 41d057137f20
Revises: 96fa1b9e43af
Create Date: 2017-10-01 17:55:00.121507

"""

# revision identifiers, used by Alembic.
revision = '41d057137f20'
down_revision = '96fa1b9e43af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
