"""initial migrating

Revision ID: 4c16054a9d8f
Revises: 2aca1e2b0da9
Create Date: 2017-10-06 11:40:58.689094

"""

# revision identifiers, used by Alembic.
revision = '4c16054a9d8f'
down_revision = '2aca1e2b0da9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
