"""initial migrating

Revision ID: 96fa1b9e43af
Revises: 456a945560f6
Create Date: 2017-10-01 11:39:21.811468

"""

# revision identifiers, used by Alembic.
revision = '96fa1b9e43af'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
