"""initial migrating

Revision ID: 9e6aabe041f3
Revises: 534990ad207d
Create Date: 2017-10-05 14:01:40.933097

"""

# revision identifiers, used by Alembic.
revision = '9e6aabe041f3'
down_revision = '534990ad207d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
