"""initial migrating

Revision ID: b978b64a4dce
Revises: 50f07f619f8f
Create Date: 2017-10-09 23:33:59.582228

"""

# revision identifiers, used by Alembic.
revision = 'b978b64a4dce'
down_revision = '50f07f619f8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
