"""修改默认字段

Revision ID: de2bb1ab0f0a
Revises: b978b64a4dce
Create Date: 2018-05-30 21:13:02.485172

"""

# revision identifiers, used by Alembic.
revision = 'de2bb1ab0f0a'
down_revision = 'b978b64a4dce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
